In [27]:
import numpy
import re

In [28]:
with open('sentences.txt', 'r') as f:
    sentences = f.read()
arr = sentences.lower().split('\n')
arr_f = arr
arr

['in comparison to dogs, cats have not undergone major changes during the domestication process.',
 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.',
 'a common interactive use of cat for a single file is to output the content of a file to standard output.',
 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.',
 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.',
 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.',
 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).',
 'however, if the output is piped or redirected, cat is unnecessary.',
 'cat with one named file is safer where human error i

In [29]:
for i in range(len(arr)):                               
    arr[i] = re.split('[^a-z]', arr[i])    
    for j in range(arr[i].count('')):        
        arr[i].remove('')
arr

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process'],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes'],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output'],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals'],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'of',
  'artificial',
  's

In [30]:
unique = list(set([word for arr_f in arr for word in arr_f]))
d={}
cnt = 0
for i in unique:                       
    d[i] = cnt
    cnt +=1
d

{'diploid': 0,
 'mavericks': 1,
 'when': 2,
 'arguments': 3,
 'allows': 4,
 'during': 5,
 'for': 6,
 'or': 7,
 'firmware': 8,
 'safer': 9,
 'upgrade': 10,
 'domestication': 11,
 'successor': 12,
 'organisms': 13,
 'useful': 14,
 'used': 15,
 'to': 16,
 'receives': 17,
 'releases': 18,
 'unnecessary': 19,
 'x': 20,
 'concatenate': 21,
 'domesticated': 22,
 'longer': 23,
 'drive': 24,
 'streams': 25,
 'wild': 26,
 'small': 27,
 'tamed': 28,
 'terms': 29,
 'animals': 30,
 'similar': 31,
 'those': 32,
 'wrong': 33,
 'store': 34,
 'most': 35,
 'moved': 36,
 'rather': 37,
 'instead': 38,
 'human': 39,
 'using': 40,
 'over': 41,
 'unix': 42,
 'too': 43,
 'interactive': 44,
 'online': 45,
 'non': 46,
 'some': 47,
 'so': 48,
 'developed': 49,
 'pipes': 50,
 'need': 51,
 'named': 52,
 'every': 53,
 'a': 54,
 'os': 55,
 'made': 56,
 'lb': 57,
 'sounds': 58,
 'learned': 59,
 'comparison': 60,
 'intel': 61,
 'closest': 62,
 'bytes': 63,
 'default': 64,
 'catenates': 65,
 'stdout': 66,
 'chromosomes

In [38]:
matrix = numpy.zeros((len(arr_f), len(unique)))
matrix.shape
for i, j in enumerate(arr):
    for z in j:
        matrix[i, d[z]] = j.count(z)
matrix.shape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
def cos_distance(x, y):
    return 1 - x@y/(numpy.sqrt(x@x)*numpy.sqrt(y@y))
distances=numpy.array([cos_distance(matrix[0],matrix[i]) for i in range(1, matrix.shape[0])])
distances

array([0.95275444, 0.86447381, 0.89517152, 0.77708871, 0.94023857,
       0.73273876, 0.92587507, 0.88427249, 0.90550888, 0.83281654,
       0.88047714, 0.83964325, 0.87035926, 0.87401184, 0.94427218,
       0.84063619, 0.9566445 , 0.94427218, 0.88854436, 0.84275727,
       0.82503645])

In [49]:
numpy.argsort(distances)[:2] + 1

array([6, 4], dtype=int32)